version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:5173
    container_name: portfolio-frontend
    networks:
      - vue-net
    volumes:
      - ./src:/usr/app/src
networks:
  vue-net:
    driver: bridge